import React from 'react';
import {
  LayoutDashboard,
  ArrowLeftRight,
  ArrowDownLeft,
  ArrowUpRight,
  WalletCards,
  ChartNoAxesCombined,
  Settings,
  Plus,
  Search,
  CalendarDays,
  Trash2,
  Pencil,
  Utensils,
  Car,
  ShoppingBag,
  BriefcaseBusiness,
  Landmark,
  Banknote,
  Smartphone,
  CreditCard,
  Laptop,
  Home,
  Zap,
  Film,
  GraduationCap,
  HeartPulse,
  Receipt,
  PiggyBank,
  TrendingUp,
  Gift,
  HelpCircle,
  Shield,
  Plane,
  Coffee,
  Fuel,
  Wifi,
  Tv,
  Store,
  DollarSign,
  CircleCheck,
  CircleAlert,
  AlertTriangle,
  X,
  Filter,
  ArrowUpDown,
  Download,
  Upload,
  RefreshCw,
  Eye,
  EyeOff,
  SlidersHorizontal,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Check,
  Clock,
  LucideIcon
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  // Navigation & Core
  LayoutDashboard,
  ArrowLeftRight,
  ArrowDownLeft,
  ArrowUpRight,
  WalletCards,
  ChartNoAxesCombined,
  Settings,
  Plus,
  Search,
  CalendarDays,
  Trash2,
  Pencil,
  SlidersHorizontal,
  Filter,
  ArrowUpDown,
  Download,
  Upload,
  RefreshCw,
  Eye,
  EyeOff,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Check,
  Clock,
  X,
  CircleCheck,
  CircleAlert,
  AlertTriangle,
  HelpCircle,

  // Categories & Accounts
  Utensils,
  Car,
  ShoppingBag,
  BriefcaseBusiness,
  Landmark,
  Banknote,
  Smartphone,
  CreditCard,
  Laptop,
  Home,
  Zap,
  Film,
  GraduationCap,
  HeartPulse,
  Receipt,
  PiggyBank,
  TrendingUp,
  Gift,
  Shield,
  Plane,
  Coffee,
  Fuel,
  Wifi,
  Tv,
  Store,
  DollarSign,
};

// Available icons selectable for categories
export const AVAILABLE_CATEGORY_ICONS = [
  { name: 'Utensils', label: 'Food & Dining' },
  { name: 'Coffee', label: 'Coffee & Snacks' },
  { name: 'ShoppingBag', label: 'Shopping' },
  { name: 'Car', label: 'Transportation' },
  { name: 'Fuel', label: 'Fuel / Gas' },
  { name: 'Home', label: 'Housing & Rent' },
  { name: 'Zap', label: 'Utilities / Bills' },
  { name: 'Wifi', label: 'Internet' },
  { name: 'Film', label: 'Entertainment' },
  { name: 'Tv', label: 'Subscriptions' },
  { name: 'HeartPulse', label: 'Healthcare' },
  { name: 'GraduationCap', label: 'Education' },
  { name: 'BriefcaseBusiness', label: 'Salary / Work' },
  { name: 'Laptop', label: 'Freelance / Tech' },
  { name: 'TrendingUp', label: 'Investments' },
  { name: 'PiggyBank', label: 'Savings' },
  { name: 'Gift', label: 'Gifts & Donations' },
  { name: 'Plane', label: 'Travel' },
  { name: 'Receipt', label: 'Taxes / Fees' },
  { name: 'Store', label: 'Groceries' },
  { name: 'Shield', label: 'Insurance' },
  { name: 'HelpCircle', label: 'General / Other' },
];

export function getIconComponent(iconName?: string): LucideIcon {
  if (!iconName) return HelpCircle;
  return ICON_MAP[iconName] || HelpCircle;
}

export function CategoryIcon({
  name,
  className = 'w-4 h-4',
}: {
  name?: string;
  className?: string;
}) {
  const Icon = getIconComponent(name);
  return React.createElement(Icon, { className });
}
